### ISSUE TITLE
gridmet varname and long_name for some variables are mis-named

### ISSUE THREAD

**Issue by rmcd-mscb** [mikejohnson51/opendap.catalog#15]
I think with some variables in gridmet, for example, "eddi14d", the varname and long_name are mis-catagorized.  Currently in the catalog they are named "category".  I think this may be a result of 2 grid variables in the opendap endpoint, ie. eddi14d and category.  In this case varname should be "eddi" and long_name should be "eddi14d".

**Comment by mikejohnson51** [comment]
hmmm yes, I didn't anticipate this in the aggregated TDS catalogs. Thanks for bringing to my attention @rmcd-mscb! I will try to make sure it captures multiple 2D variables in these cases.

**Comment by mikejohnson51** [comment]
Actually I take that back - both 2D variables are captured in the catalog for each endpoint and the varname and long_names appear correct. 

This is were the distinction between variable and varname might need to be made clearer. `variable` is the description of the file (in this case eddi14) varname is the name of the individual grids in the file (eddi14 and category).

In _most_ case varname and variable are the same:

Where were you seeing them misaligned or is the variable/varname distinction to vague?

### Example

``` r
jsonlite::read_json('https://mikejohnson51.github.io/opendap.catalog/cat_params.json', 
          simplifyVector = TRUE) |> 
  dplyr::filter(grepl('eddi14d', URL))
#>        id grid_id
#> 1 gridmet     172
#> 2 gridmet     172
#>                                                                                                  URL
#> 1 http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_met_eddi14d_1979_CurrentYear_CONUS.nc
#> 2 http://thredds.northwestknowledge.net:8080/thredds/dodsC/agg_met_eddi14d_1979_CurrentYear_CONUS.nc
#>   tiled variable  varname long_name T_name      duration interval nT units
#> 1        eddi14d category  category    day 1979-01-01/..   1 days NA      
#> 2        eddi14d     eddi   eddi14d    day 1979-01-01/..   1 days NA      
#>   model ensemble scenario
#> 1  <NA>     <NA>    total
#> 2  <NA>     <NA>    total
```

<sup>Created on 2022-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rmcd-mscb** [comment]
Ah thanks Mike - sorry to lead you down my error in processing.  I think - I didn't realize when first getting acquainted the the json file, that there were multiple entries for the eddi4d variable (for example).
